# Generated by Django 4.1.7 on 2023-03-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.IntegerField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_date', models.DateField(auto_now=True)),
                ('birth_date', models.DateField(blank=True)),
            ],
        ),
    ]
