# Generated by Django 4.1.7 on 2023-03-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField(auto_now=True)),
                ('until', models.DateField(blank=True, default='yet')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('registration_date', models.DateField(auto_now=True)),
                ('birth_date', models.DateField(blank=True)),
            ],
        ),
    ]
