# Generated by Django 4.1.7 on 2023-03-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
