# Generated by Django 4.1.7 on 2023-03-09 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='players',
            name='teams',
            field=models.ManyToManyField(through='players.Belong', to='teams.team'),
        ),
        migrations.AddField(
            model_name='belong',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players'),
        ),
        migrations.AddField(
            model_name='belong',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
