# Generated by Django 4.1.7 on 2023-03-08 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_players_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Belong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateField(auto_now=True)),
                ('until', models.DateField(blank=True, default='yet')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.players')),
            ],
        ),
    ]
