# Generated by Django 4.1.7 on 2023-03-08 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('players', '0003_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='belong',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='players',
            name='teams',
            field=models.ManyToManyField(through='players.Belong', to='teams.team'),
        ),
    ]
